async function promiseRejectionAsync() {
   try {
       await new Promise((_, reject) => setTimeout(() => reject(new Error("Oops!")), 1000));
   } catch (error) {
       console.error(error.message);
   }
}

// Тази функция promiseRejectionAsync() е асинхронна и използва async ключовата дума, която я прави асинхронна. Тя се опитва да изпълни промис, който ще бъде отхвърлен след една секунда (1000 милисекунди).Този код създава промис, който ще бъде отхвърлен с грешка "Oops!" след една секунда.

// С try...catch блока, функцията се опитва да изпълни кода в try блока. В try блока се използва await, което означава, че изчаква промисът да бъде разрешен или отхвърлен, преди да продължи напред с изпълнението на кода.

// Ако промисът бъде отхвърлен, изпълнението се премества към catch блока, където се хваща грешката (Error), предадена от отхвърления промис. Тук се извежда съобщението за грешка в конзолата чрез console.error(error.message).

// Така че, ако този промис бъде отхвърлен (след една секунда), ще бъде хваната грешката и съобщението й ще бъде изведено в конзолата.